export const types={
      //AUTH ACTIONS//
  LOGIN_START: "LOGIN_START",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",

  LOGOUT_START: "LOGOUT_START",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAIL: "LOGOUT_FAIL",

  CREATE_USER_START: "CREATE_USER_START",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAIL: "CREATE_USER_FAIL",

  CREATE_PROFILE_START: "CREATE_PROFILE_START",
  CREATE_PROFILE_SUCCESS: "CREATE_PROFILE_SUCCESS",
  CREATE_PROFILE_FAIL: "CREATE_PROFILE_FAIL",
  
  GET_PROFILE_START: "GET_PROFILE_START",
  GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
  GET_PROFILE_FAIL: "GET_PROFILE_FAIL",

  GET_USER_START: "GET_USER_START",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAIL: "GET_USER_FAIL",

  UPDATE_USER_START: "UPDATE_USER_START",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAIL: "UPDATE_USER_FAIL",
  
  GET_PASS_START: "GET_PASS_START",
  GET_PASS_SUCCESS: "GET_PASS_SUCCESS",
  GET_PASS_FAIL: "GET_PASS_FAIL",

  WELCOME_BACK: "WELCOME_BACK",
  //AUTH ACTIONS//

  //POST ACTIONS//
  GET_BLOG_START: "GET_BLOG_START",
  GET_BLOG_SUCCESS: "GET_BLOG_SUCCESS",
  GET_BLOG_FAIL: "GET_BLOG_FAIL",

  DELETE_BLOG_START: "DELETE_BLOG_START",
  DELETE_BLOG_SUCCESS: "DELETE_BLOG_SUCCESS",
  DELETE_BLOG_FAIL: "DELETE_BLOG_FAIL",

  POST_NEW_BLOG_START: "POST_NEW_BLOG_START",
  POST_NEW_BLOG_SUCCESS: "POST_NEW_BLOG_SUCCESS",
  POST_NEW_BLOG_FAIL: "POST_NEW_BLOG_FAIL",

  //POST ACTIONS//

  //COMMENT ACTIONS//
  POST_NEW_COMMENT_START: "POST_NEW_COMMENT_START",
  POST_NEW_COMMENT_SUCCESS: "POST_NEW_COMMENT_SUCCESS",
  POST_NEW_COMMENT_FAIL: "POST_NEW_COMMENT_FAIL",

  DELETE_COMMENT_START: "DELETE_COMMENT_START",
  DELETE_COMMENT_SUCCESS: "DELETE_COMMENT_SUCCESS",
  DELETE_COMMENT_FAIL: "DELETE_COMMENT_FAIL",

  //COMMENT ACTIONS//
}